backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Template", name: template, widget: "hidden" }
      - { label: Date, name: date, widget: datetime }
      - { label: Title, name: title, widget: string }
      - { label: Image, name: image, widget: image }
      - { label: Body, name: body, widget: markdown }
